---

kein auskommentieren

alles was man per ssh machen kann mit dem shell module machen

module bieten idempotence und vereinfachen sachen

hello world
idempotenz

pro demo eine seite bullet points worum es geht




- name: Deploy - Preperation Phase
  hosts: app_servers
  gather_facts: false
  max_fail_percentage: 0.00000000000001
  vars:
    source_repository: /home/holger/Dropbox/ipc-example-project
    target_repository: /home/holger/ipc-example-target/repository
    releases_directory: /home/holger/ipc-example-target/releases
  tasks:
  - name: git checkout
    git:
      repo: "{{source_repository}}"
      dest: "{{target_repository}}"
      version: HEAD
    register: git_result
    # failed_when: "'{{inventory_hostname}}' == '127.0.0.1'"
  - debug:
      msg: >
        git update from {{git_result.before}} to: {{git_result.after}}
  - set_fact:
      next_release_directory: "{{releases_directory}}/{{git_result.after}}"
  - name: create release
    git:
      repo: "{{target_repository}}"
      dest: "{{next_release_directory}}"
      version: '{{git_result.after}}'

- name: Deploy - Activation Phase
  max_fail_percentage: 0.00000000000001
  vars:
    release_symlink: ~/Dropbox/ipc-example-target/current-release
  hosts: app_servers
  gather_facts: false
  tasks:
  - name: update release symlink
    file:
      state: link
      src: "{{next_release_directory}}"
      path: "{{release_symlink}}"
